name: Node.js other branches

on:
  push:
    branches-ignore:
      - gh-pages
      - master

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - name: Generate jsdoc
      run: node ./node_modules/.bin/jsdoc ./src/transfData.js -d ./documentation
    - name: Saving documentation as artifact
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: documentation
        path: documentation
      
      
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: |
           npm start &
           sleep 20
           curl localhost:8080
    - run: npm test
    
      env:
        CI: true
        
    
    
          
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Dowloading docs stored as artifacts
      uses: actions/download-artifact@v1
      with:
        name: documentation
    - name: Deploy on GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.cows_CI }}
        BRANCH: gh-pages-${{github.ref}}
        FOLDER: 'documentation'
