name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        
        
  jsdoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
    - name: Use Node.js $ 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x  
    - run: npm install
    - run: node ./node_modules/.bin/jsdoc ./src/transfData.js -d ./documentation
    - name: Saving site as artifact
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: documentation
        path: documentation
    
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./documentation

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.cows_CI }}
          publish_dir: ./documentation
          
  deploy:
    needs: [jsdoc]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Dowloading docs stored as artifacts
      uses: actions/download-artifact@v1
      with:
        name: documentation
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy on GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.cows_CI }}
        BRANCH: gh-pages
        FOLDER: documentation
    
